# Generated by Django 2.2.2 on 2019-11-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gallery',
        ),
    ]
